site_name: Adventronics Calendar 
site_description: Adventronics Calendar
site_author: Future Learning Unit (FLU)
repo_name: 'Adventronics Calendar'
repo_url: 'https://github.com/fablabbcn/adventronics/'
copyright: 'Copyleft 2023 FLB - GNU Free Documentation License'

nav:
  - Home:
    - index.md
  - Barduino:
    - barduino.md
  - How to particpate?:
    - howto.md
  - Solutions:
    - Day 1: solutions/01/01.md
  - Solution template:
    - template.md


theme: 
  name: 'material'
  icon:
    annotation: material/plus-circle 
    admonition:
      note: material/party-popper
      tip: material/balloon
      question: material/robot
      warning: material/cookie
      bug: material/candle
      example: material/snowflake
  logo: images/flb.svg
  favicon: images/Barduino4.svg
  features:
    - instant
    - navigation.expand
    - tabs
    - toc.autohide
    - navigation.tabs
  palette:
    scheme: slate
    primary: black
      

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

